### ISSUE TITLE
When a Safari window is launched, sometimes it doesn't match the specified browser size

### ISSUE THREAD

**Issue by aroweaerian** [smashtestio/smashtest#57] opened 2019-12-17 14:00 UTC
Even though the desktop is set at 1920x1080(in smashtest), the browser sometimes automatically loads at 800x562. This is intermittent, however, my test relies on the click coordinates. 

The same also happens when using the simple test, below:

`$ Open Safari

    Desktop
        ..
        Navigate to "google.com"
        Wait '3' secs`

**Comment by vptes1** [comment] 2019-12-17 15:55
I wasn't able to reproduce locally, but did add an `await` keyword on the line that was setting the viewport size. That should hopefully fix the problem. Please upgrade to the latest version (1.6.17) and try again.

**Comment by vptes1** [comment] 2019-12-18 17:44
Is this ticket ok to close?

**Comment by vptes1** [comment] 2019-12-21 01:37
Closing since I cannot reproduce and nobody is complaining about this problem anymore.

**Closed by vptes1** 2019-12-21 01:37 UTC
Labels: bug
